/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nhom13_shopquanaothethao;

import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
/**
 *
 * @author ACER
 */
public class BanHangModule extends javax.swing.JFrame {

    /**
     * Creates new form BanHangModule
     */
    Connection con;
    Product pro;
    BanHangForm BHF;
    String sSize;
    public BanHangModule(Product p, BanHangForm bf) {
        initComponents();
        this.pro = p;
        this.BHF = bf;
        rdo_S.setText(pro.getProductSize());
        lbl_TinhTrang.setVisible(false);
        lbl_Tittle.setText(pro.getTensp());
    }

    private void SLTon(String ten, String size)
    {
        try
        {
            con = nhom13_shopquanaothethao.Connection.GetConnection();
            String sql = "SELECT SoLuongTon, TinhTrang FROM SANPHAM WHERE TENSANPHAM = N'" + ten + "' AND SIZE = '" + size +"'";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            if (rs.next())
            {
                txt_SLTon.setText(String.valueOf(rs.getInt("SoLuongTon")));
                lbl_TinhTrang.setVisible(true);
                if (Integer.parseInt(txt_SLTon.getText()) != 0)
                {
                    lbl_TinhTrang.setText("Còn Hàng");
                    lbl_TinhTrang.setForeground(Color.GREEN);
                }
                else if (rs.getString("TinhTrang").equals("Chưa Nhập Sản Phẩm"))
                {
                    lbl_TinhTrang.setText("Chưa nhập sản phẩm này");
                    lbl_TinhTrang.setForeground(Color.red);
                }
                else
                {
                    lbl_TinhTrang.setText("Hết Hàng");
                    lbl_TinhTrang.setForeground(Color.red);
                }
            }
            else
            {
                txt_SLTon.setText(0+"");
                lbl_TinhTrang.setVisible(true);
                lbl_TinhTrang.setText("Chưa có sản phẩm này");
                lbl_TinhTrang.setForeground(Color.red);
            }
            st.close();
            rs.close();
            con.close();
        }
        catch (SQLException e)
        {
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngr = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lbl_Exit = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btn_Save = new javax.swing.JButton();
        btn_Huy = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        rdo_S = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        txt_SLTon = new javax.swing.JTextField();
        lbl_TinhTrang = new javax.swing.JLabel();
        txt_SL = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lbl_Tittle = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(3, 172, 220));

        lbl_Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Cancel.png"))); // NOI18N
        lbl_Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_ExitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_Exit))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_Exit))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        btn_Save.setBackground(new java.awt.Color(255, 132, 44));
        btn_Save.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Save.setForeground(new java.awt.Color(255, 255, 255));
        btn_Save.setText("Lưu");
        btn_Save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SaveActionPerformed(evt);
            }
        });

        btn_Huy.setBackground(new java.awt.Color(153, 153, 153));
        btn_Huy.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Huy.setForeground(new java.awt.Color(255, 255, 255));
        btn_Huy.setText("Hủy");
        btn_Huy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HuyActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Size - SL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(208, 182));

        btngr.add(rdo_S);
        rdo_S.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdo_S.setText("S");
        rdo_S.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rdo_S.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rdo_SItemStateChanged(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("SL Tồn:");

        txt_SLTon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_SLTon.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_SLTon.setEnabled(false);

        lbl_TinhTrang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_TinhTrang.setText("SL Tồn:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_TinhTrang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(rdo_S)
                            .addComponent(txt_SLTon, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 116, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(rdo_S)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_SLTon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_TinhTrang)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        txt_SL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_SL.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_SL.setEnabled(false);
        txt_SL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_SLKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(3, 172, 220));
        jLabel2.setText("Chọn size và số lượng");

        lbl_Tittle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_Tittle.setText("jLabel3");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Nhập SL:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Tittle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_Save)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Huy))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_SL, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_Tittle)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_SL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Huy, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Save, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ExitMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_lbl_ExitMouseClicked

    private void rdo_SItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rdo_SItemStateChanged
        // TODO add your handling code here:
        if (rdo_S.isSelected())
        {
            SLTon(pro.getTensp(), rdo_S.getText());
            txt_SL.setEnabled(true);
            txt_SL.requestFocus();
            sSize = rdo_S.getText();
        }
        else
        {
            txt_SLTon.setText("");
            txt_SL.setEnabled(false);
        }
    }//GEN-LAST:event_rdo_SItemStateChanged

    private void btn_HuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HuyActionPerformed
        // TODO add your handling code here:
        txt_SL.setText("");
        txt_SL.setEnabled(false);
        btngr.clearSelection();
        lbl_TinhTrang.setText("");
        lbl_TinhTrang.setVisible(false);
    }//GEN-LAST:event_btn_HuyActionPerformed

    private void btn_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SaveActionPerformed
        // TODO add your handling code here:
        if (lbl_TinhTrang.getText().equals("Chưa có sản phẩm này"))
        {
            JOptionPane.showMessageDialog(rootPane, "Chưa có sản phẩm này", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        else
        {
            if (txt_SL.getText().trim().isEmpty())
            {
                JOptionPane.showMessageDialog(rootPane, "Vui lòng kiểm tra lại thông tin", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            else if (Integer.parseInt(txt_SL.getText().trim()) > Integer.parseInt(txt_SLTon.getText().trim()))
            {
                JOptionPane.showMessageDialog(rootPane, "Vui lòng kiểm tra lại số lượng <= số lượng tồn kho", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            else if (Integer.parseInt(txt_SL.getText().trim()) == 0)
            {
                JOptionPane.showMessageDialog(rootPane, "Vui lòng không nhập số lượng = 0", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            else if (Integer.parseInt(txt_SLTon.getText().trim()) == 0)
            {
                JOptionPane.showMessageDialog(rootPane, "Hết hàng vui lòng chọn size khác", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
        }
        for (int i = 0; i < BHF.tblmodel.getRowCount(); i++)
        {
            if (BHF.tblmodel.getValueAt(i, 1).toString().equals(pro.getTensp()) && BHF.tblmodel.getValueAt(i, 3).toString().equals(sSize))
            {
                BHF.tblmodel.setValueAt(txt_SL.getText(), i, 2);
                BHF.tblmodel.setValueAt(String.valueOf(Integer.parseInt(BHF.tblmodel.getValueAt(i, 2).toString()) * Integer.parseInt(BHF.tblmodel.getValueAt(i, 4).toString())), i, 5);
                BHF.GetTotal();
                txt_SL.setText("");
                txt_SL.requestFocus();
                return;
            }
        }
        Object[] row = { 0, pro.getTensp(), txt_SL.getText(),  sSize, String.valueOf(pro.getGiaban()), String.valueOf(Integer.parseInt(txt_SL.getText()) * pro.getGiaban()) };
        BHF.tblmodel.addRow(row);
        BHF.loadSTT();
        BHF.GetTotal();
        txt_SL.setText("");
        txt_SL.requestFocus();
    }//GEN-LAST:event_btn_SaveActionPerformed

    private void txt_SLKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_SLKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar()))
        {
            evt.consume();
        }
    }//GEN-LAST:event_txt_SLKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BanHangModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BanHangModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BanHangModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BanHangModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BanHangForm bf = new BanHangForm();
                Product p = new Product(bf, null, "",  "", "", "", "", 0, "");
                new BanHangModule(p, bf).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_Huy;
    public javax.swing.JButton btn_Save;
    public javax.swing.ButtonGroup btngr;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JLabel lbl_Exit;
    public javax.swing.JLabel lbl_TinhTrang;
    public javax.swing.JLabel lbl_Tittle;
    public javax.swing.JRadioButton rdo_S;
    public javax.swing.JTextField txt_SL;
    public javax.swing.JTextField txt_SLTon;
    // End of variables declaration//GEN-END:variables
}
