/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nhom13_shopquanaothethao;

import java.awt.Color;
import java.time.DayOfWeek;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author ACER
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        lbl_TrangChuMouseClicked(null);
        
        lbl_TrangChuMouseClicked(null);

        LocalDate currentTime = LocalDate.now();

        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("'Ngày' dd/MM/yyyy");
        String formattedTime = currentTime.format(formatter);
        lbl_Time.setText(formattedTime);
    }
    
    int width = 170;
    int height = 750;
    private void openMenubar()
    {
        new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i = 0; i < width; i++)
                {
                    pnMenu.setSize(i, height);
                    try 
                    {
                        Thread.sleep(2);
                    } 
                    catch (InterruptedException ex) {
                        Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }).start();
    }
    private void closeMenubar()
    {
        new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i = width; i > 0; i--)
                {
                    pnMenu.setSize(i, height);
                    try 
                    {
                        Thread.sleep(2);
                    } 
                    catch (InterruptedException ex) {
                        Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }).start();
    }
    
    private JFrame activeJFrame = null;
    private void openChildJFrame(JFrame childJFrame)
    {
        if (activeJFrame != null)
        {
            activeJFrame.dispose();
        }
        else
        {
            activeJFrame = childJFrame;
            childJFrame.setBounds(0, 0, pnChilds.getWidth(), pnChilds.getHeight());
            pnChilds.removeAll();
            pnChilds.add(activeJFrame.getContentPane());
            pnChilds.revalidate();
            pnChilds.repaint();
        }
    }
    private void lblClear()
    {
        lbl_TrangChu.setForeground(Color.WHITE);
        lbl_SanPham.setForeground(Color.WHITE);
        lbl_BanHang.setForeground(Color.WHITE);
        lbl_KhoHang.setForeground(Color.WHITE);
        lbl_NCC.setForeground(Color.WHITE);
        lbl_NV.setForeground(Color.WHITE);
        lbl_Account.setForeground(Color.WHITE);
        lbl_ThongKe.setForeground(Color.WHITE);
    }
    
    private String getDayOfWeekInVietnamese(DayOfWeek dayOfWeek) 
    {
        switch (dayOfWeek) 
        {
            case SUNDAY:
                return "Chủ nhật";
            case MONDAY:
                return "Thứ hai";
            case TUESDAY:
                return "Thứ ba";
            case WEDNESDAY:
                return "Thứ tư";
            case THURSDAY:
                return "Thứ năm";
            case FRIDAY:
                return "Thứ sáu";
            case SATURDAY:
                return "Thứ bảy";
            default:
                return "";
        }
    }
    public void setIDNV(String id) 
    {
        lbl_IDNV.setText(id);
    }

    public void setUserName(String username) 
    {
        lbl_TenNV.setText(username);
    }

    public void setRole(String role) 
    {
        lbl_Role.setText("Chức Vụ: " + role);
    }
    public void checkUserRole() 
    {
        if (!lbl_Role.getText().equals("Chức Vụ: Quản Lý Cửa Hàng")) 
        {
            lbl_ThongKe.setVisible(false);
            lbl_Account.setVisible(false);
            lbl_NV.setVisible(false);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMenu = new javax.swing.JPanel();
        lbl_SanPham = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_LogOut = new javax.swing.JLabel();
        lbl_NCC = new javax.swing.JLabel();
        lbl_NV = new javax.swing.JLabel();
        lbl_Account = new javax.swing.JLabel();
        lbl_ThongKe = new javax.swing.JLabel();
        lbl_BanHang = new javax.swing.JLabel();
        lbl_KhoHang = new javax.swing.JLabel();
        lbl_TrangChu = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblCloseMenu = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbl_Menu = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl_IDNV = new javax.swing.JLabel();
        lbl_TenNV = new javax.swing.JLabel();
        lbl_Role = new javax.swing.JLabel();
        lbl_Time = new javax.swing.JLabel();
        pnChilds = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnMenu.setBackground(new java.awt.Color(3, 172, 220));
        pnMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_SanPham.setBackground(new java.awt.Color(3, 172, 220));
        lbl_SanPham.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_SanPham.setForeground(new java.awt.Color(255, 255, 255));
        lbl_SanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-sports-teams-30.png"))); // NOI18N
        lbl_SanPham.setText("Sản phẩm");
        lbl_SanPham.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_SanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_SanPhamMouseClicked(evt);
            }
        });
        pnMenu.add(lbl_SanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 143, 170, 45));

        jLabel2.setBackground(new java.awt.Color(3, 172, 220));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Xin Chào");
        pnMenu.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 138, 52));

        lbl_LogOut.setBackground(new java.awt.Color(3, 172, 220));
        lbl_LogOut.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_LogOut.setForeground(new java.awt.Color(255, 255, 255));
        lbl_LogOut.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_LogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-log-out-30.png"))); // NOI18N
        lbl_LogOut.setText("Đăng xuất");
        lbl_LogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_LogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_LogOutMouseClicked(evt);
            }
        });
        pnMenu.add(lbl_LogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 684, 170, 66));

        lbl_NCC.setBackground(new java.awt.Color(3, 172, 220));
        lbl_NCC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_NCC.setForeground(new java.awt.Color(255, 255, 255));
        lbl_NCC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-supplier-30.png"))); // NOI18N
        lbl_NCC.setText("Nhà cung cấp");
        lbl_NCC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_NCC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_NCCMouseClicked(evt);
            }
        });
        pnMenu.add(lbl_NCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 296, 170, 45));

        lbl_NV.setBackground(new java.awt.Color(3, 172, 220));
        lbl_NV.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_NV.setForeground(new java.awt.Color(255, 255, 255));
        lbl_NV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-staff-30.png"))); // NOI18N
        lbl_NV.setText("Nhân viên");
        lbl_NV.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_NV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_NVMouseClicked(evt);
            }
        });
        pnMenu.add(lbl_NV, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 347, 170, 45));

        lbl_Account.setBackground(new java.awt.Color(3, 172, 220));
        lbl_Account.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_Account.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Account.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Account.png"))); // NOI18N
        lbl_Account.setText("Tài khoản");
        lbl_Account.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_Account.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_AccountMouseClicked(evt);
            }
        });
        pnMenu.add(lbl_Account, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 398, 170, 45));

        lbl_ThongKe.setBackground(new java.awt.Color(3, 172, 220));
        lbl_ThongKe.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_ThongKe.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-analytics-30.png"))); // NOI18N
        lbl_ThongKe.setText("Thống kê");
        lbl_ThongKe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_ThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_ThongKeMouseClicked(evt);
            }
        });
        pnMenu.add(lbl_ThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 449, 170, 45));

        lbl_BanHang.setBackground(new java.awt.Color(3, 172, 220));
        lbl_BanHang.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_BanHang.setForeground(new java.awt.Color(255, 255, 255));
        lbl_BanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-create-order-30.png"))); // NOI18N
        lbl_BanHang.setText("Bán hàng");
        lbl_BanHang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_BanHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_BanHangMouseClicked(evt);
            }
        });
        pnMenu.add(lbl_BanHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 194, 170, 45));

        lbl_KhoHang.setBackground(new java.awt.Color(3, 172, 220));
        lbl_KhoHang.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_KhoHang.setForeground(new java.awt.Color(255, 255, 255));
        lbl_KhoHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-warehouse-30.png"))); // NOI18N
        lbl_KhoHang.setText("Nhập hàng");
        lbl_KhoHang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_KhoHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_KhoHangMouseClicked(evt);
            }
        });
        pnMenu.add(lbl_KhoHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 245, 170, 45));

        lbl_TrangChu.setBackground(new java.awt.Color(3, 172, 220));
        lbl_TrangChu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_TrangChu.setForeground(new java.awt.Color(255, 255, 255));
        lbl_TrangChu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Home.png"))); // NOI18N
        lbl_TrangChu.setText("Trang chủ");
        lbl_TrangChu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_TrangChu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_TrangChuMouseClicked(evt);
            }
        });
        pnMenu.add(lbl_TrangChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 92, 170, 45));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        pnMenu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 58, 170, -1));

        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        pnMenu.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 676, 170, -1));

        lblCloseMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-close-20.png"))); // NOI18N
        lblCloseMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCloseMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMenuMouseClicked(evt);
            }
        });
        pnMenu.add(lblCloseMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 6, -1, -1));

        getContentPane().add(pnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 0, 750));

        jPanel1.setBackground(new java.awt.Color(3, 172, 220));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-menu-50.png"))); // NOI18N
        lbl_Menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_Menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_MenuMouseClicked(evt);
            }
        });
        jPanel1.add(lbl_Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 0, -1, 60));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/User.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 30, 60));

        lbl_IDNV.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_IDNV.setForeground(new java.awt.Color(255, 255, 255));
        lbl_IDNV.setText("jLabel5");
        jPanel1.add(lbl_IDNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        lbl_TenNV.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_TenNV.setForeground(new java.awt.Color(255, 255, 255));
        lbl_TenNV.setText("jLabel6");
        jPanel1.add(lbl_TenNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, -1, -1));

        lbl_Role.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_Role.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Role.setText("jLabel7");
        jPanel1.add(lbl_Role, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, -1, -1));

        lbl_Time.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_Time.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Time.setText("jLabel8");
        jPanel1.add(lbl_Time, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 60));

        javax.swing.GroupLayout pnChildsLayout = new javax.swing.GroupLayout(pnChilds);
        pnChilds.setLayout(pnChildsLayout);
        pnChildsLayout.setHorizontalGroup(
            pnChildsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1370, Short.MAX_VALUE)
        );
        pnChildsLayout.setVerticalGroup(
            pnChildsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );

        getContentPane().add(pnChilds, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1370, 690));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_MenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_MenuMouseClicked
        // TODO add your handling code here:
        openMenubar();
    }//GEN-LAST:event_lbl_MenuMouseClicked

    private void lblCloseMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMenuMouseClicked
        // TODO add your handling code here:
        closeMenubar();
    }//GEN-LAST:event_lblCloseMenuMouseClicked

    private void lbl_TrangChuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_TrangChuMouseClicked
        // TODO add your handling code here:
        lblClear();
        openChildJFrame(new TrangChuForm());
        lbl_TrangChu.setForeground(Color.GREEN);
        activeJFrame = null;
    }//GEN-LAST:event_lbl_TrangChuMouseClicked

    private void lbl_LogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_LogOutMouseClicked
        // TODO add your handling code here:
        this.dispose();
        LoginForm login = new LoginForm();
        login.setVisible(true);
    }//GEN-LAST:event_lbl_LogOutMouseClicked

    private void lbl_AccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_AccountMouseClicked
        // TODO add your handling code here:
        lblClear();
        openChildJFrame(new AccountForm());
        lbl_Account.setForeground(Color.GREEN);
        activeJFrame = null;
    }//GEN-LAST:event_lbl_AccountMouseClicked

    private void lbl_BanHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_BanHangMouseClicked
        // TODO add your handling code here:
        lblClear();
        BanHangForm bhf = new BanHangForm();
        bhf.lbl_IDNV.setText(lbl_IDNV.getText());
        bhf.lbl_TenNV.setText(lbl_TenNV.getText());
        bhf.lbl_Role.setText(lbl_Role.getText());
        bhf.setVisible(true);
        lbl_BanHang.setForeground(Color.GREEN);
        lbl_TrangChuMouseClicked(null);
    }//GEN-LAST:event_lbl_BanHangMouseClicked

    private void lbl_KhoHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_KhoHangMouseClicked
        // TODO add your handling code here:
        lblClear();
        KhoHangForm khf = new KhoHangForm();
        khf.lbl_IDNV.setText(lbl_IDNV.getText());
        khf.lbl_TenNV.setText(lbl_TenNV.getText());
        khf.lbl_Role.setText(lbl_Role.getText());
        khf.setVisible(true);
        lbl_KhoHang.setForeground(Color.GREEN);
        lbl_TrangChuMouseClicked(null);
    }//GEN-LAST:event_lbl_KhoHangMouseClicked

    private void lbl_NCCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_NCCMouseClicked
        lblClear();
        openChildJFrame(new NhaCungCapForm());
        lbl_NCC.setForeground(Color.GREEN);
        activeJFrame = null;
    }//GEN-LAST:event_lbl_NCCMouseClicked

    private void lbl_SanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_SanPhamMouseClicked
        lblClear();
        openChildJFrame(new SanPhamForm(this));
        lbl_SanPham.setForeground(Color.GREEN);
        activeJFrame = null;
    }//GEN-LAST:event_lbl_SanPhamMouseClicked

    private void lbl_NVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_NVMouseClicked
        // TODO add your handling code here:
        lblClear();
        openChildJFrame(new NhanVienForm());
        lbl_NV.setForeground(Color.GREEN);
        activeJFrame = null;
    }//GEN-LAST:event_lbl_NVMouseClicked

    private void lbl_ThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ThongKeMouseClicked
        // TODO add your handling code here:
        lblClear();
        openChildJFrame(new ThongKeForm());
        lbl_ThongKe.setForeground(Color.GREEN);
        activeJFrame = null;
    }//GEN-LAST:event_lbl_ThongKeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lblCloseMenu;
    public javax.swing.JLabel lbl_Account;
    public javax.swing.JLabel lbl_BanHang;
    public javax.swing.JLabel lbl_IDNV;
    public javax.swing.JLabel lbl_KhoHang;
    public javax.swing.JLabel lbl_LogOut;
    public javax.swing.JLabel lbl_Menu;
    public javax.swing.JLabel lbl_NCC;
    public javax.swing.JLabel lbl_NV;
    public javax.swing.JLabel lbl_Role;
    public javax.swing.JLabel lbl_SanPham;
    public javax.swing.JLabel lbl_TenNV;
    public javax.swing.JLabel lbl_ThongKe;
    public javax.swing.JLabel lbl_Time;
    public javax.swing.JLabel lbl_TrangChu;
    public javax.swing.JPanel pnChilds;
    public javax.swing.JPanel pnMenu;
    // End of variables declaration//GEN-END:variables
}
