/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nhom13_shopquanaothethao;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.table.DefaultTableModel;
import raven_cell.TableActionCellEditor;
import raven_cell.TableActionCellRender;
import raven_cell.TableActionEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class NhanVienForm extends javax.swing.JFrame {
    Connection con;
    DefaultTableModel tblmodel;

    /**
     * Creates new form NhanVienForm
     */
    public NhanVienForm() {
        initComponents();
        TableActionEvent event = new TableActionEvent() {
            @Override
            public void onEdit(int row) {
                NhanVienModule acc = null;
                try {
                    acc = new NhanVienModule(NhanVienForm.this,false);
                } catch (SQLException ex) {
                    Logger.getLogger(NhanVienForm.class.getName()).log(Level.SEVERE, null, ex);
                }
                    acc.txt_MaNV.setText(table_NhanVien.getValueAt(row, 0).toString());
                    acc.txt_TenNV.setText(table_NhanVien.getValueAt(row, 1).toString());
                    acc.txt_NgaySinh.setText(table_NhanVien.getValueAt(row, 2).toString());
                    acc.cbb_GT.setSelectedItem(table_NhanVien.getValueAt(row, 3).toString());
                    acc.txt_DiaChi.setText(table_NhanVien.getValueAt(row, 4).toString());
                    acc.txt_SDT.setText(table_NhanVien.getValueAt(row, 5).toString());
                    acc.txt_Email.setText(table_NhanVien.getValueAt(row, 6).toString());
                    acc.cbb_VTCV.setSelectedItem(table_NhanVien.getValueAt(row, 7).toString());
                    acc.txt_Luong.setText(table_NhanVien.getValueAt(row, 8).toString());
                    acc.txt_NVL.setText(table_NhanVien.getValueAt(row, 9).toString());
                    acc.cbb_IDTaiKhoan.setSelectedItem(table_NhanVien.getValueAt(row, 10).toString());
                    
                    acc.txt_TenNV.requestFocus();
                    acc.setVisible(true);
                    
            }

            @Override
            public void onDelete(int row) {
                if(table_NhanVien.isEditing())
                {
                    table_NhanVien.getCellEditor().stopCellEditing();
                }
                if (JOptionPane.showConfirmDialog(rootPane, "Bạn có muốn xóa tài khoản này không?", "Thông Báo", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE) == JOptionPane.YES_OPTION)
                {
                    try
                    {
                        con = nhom13_shopquanaothethao.Connection.GetConnection();
                        String sql = "DELETE NHANVIEN WHERE IDNhanVien = '" + tblmodel.getValueAt(row, 0).toString() + "'";
                        Statement st = con.createStatement();
                        int x = st.executeUpdate(sql);
                        if (x >= 1)
                        {
                            JOptionPane.showMessageDialog(rootPane, "Xóa Thành Công", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
                            st.close();
                            con.close();
                            loadDataTbl();
                        }
                    }
                    catch (SQLException e)
                    {
                        JOptionPane.showMessageDialog(rootPane, e.toString(), "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
                        
                    }
                }
            }
        };
        
        table_NhanVien.getColumnModel().getColumn(11).setCellRenderer(new TableActionCellRender());
        table_NhanVien.getColumnModel().getColumn(11).setCellEditor(new TableActionCellEditor(event));
        tblmodel = (DefaultTableModel) table_NhanVien.getModel();
        loadDataTbl();
        loadDataCBB();
        txt_TimKiem.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Search();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        info_NV = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_MaNV = new javax.swing.JTextField();
        txt_TenNV = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_GT = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_EmailNV = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_SDTNV = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_DiaChi = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_Luong = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_IDTaiKhoan = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_VTCV = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        cmb_TimKiem = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        txt_TimKiem = new javax.swing.JTextField();
        btn_AddTK = new javax.swing.JButton();
        btn_ResetSearch = new javax.swing.JButton();
        txt_NgaySinh = new javax.swing.JTextField();
        txt_NVL = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_NhanVien = new javax.swing.JTable();

        jTextField2.setText("jTextField1");
        jTextField2.setMaximumSize(new java.awt.Dimension(145, 29));
        jTextField2.setMinimumSize(new java.awt.Dimension(145, 29));
        jTextField2.setPreferredSize(new java.awt.Dimension(145, 29));

        jLabel2.setText("jLabel1");
        jLabel2.setMaximumSize(new java.awt.Dimension(124, 23));
        jLabel2.setMinimumSize(new java.awt.Dimension(124, 23));
        jLabel2.setPreferredSize(new java.awt.Dimension(124, 23));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1370, 679));
        setPreferredSize(new java.awt.Dimension(1370, 679));
        setSize(new java.awt.Dimension(1370, 679));

        info_NV.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin nhân viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        info_NV.setMaximumSize(new java.awt.Dimension(1147, 295));
        info_NV.setMinimumSize(new java.awt.Dimension(1147, 295));
        info_NV.setPreferredSize(new java.awt.Dimension(1147, 295));

        jLabel1.setText("Mã Nhân Viên");
        jLabel1.setMaximumSize(new java.awt.Dimension(96, 18));
        jLabel1.setMinimumSize(new java.awt.Dimension(96, 18));
        jLabel1.setPreferredSize(new java.awt.Dimension(96, 18));

        txt_MaNV.setEnabled(false);
        txt_MaNV.setMaximumSize(new java.awt.Dimension(160, 25));
        txt_MaNV.setMinimumSize(new java.awt.Dimension(160, 25));
        txt_MaNV.setPreferredSize(new java.awt.Dimension(160, 25));

        txt_TenNV.setEnabled(false);
        txt_TenNV.setMaximumSize(new java.awt.Dimension(160, 25));
        txt_TenNV.setMinimumSize(new java.awt.Dimension(160, 25));
        txt_TenNV.setPreferredSize(new java.awt.Dimension(160, 25));

        jLabel3.setText("Tên Nhân Viên");
        jLabel3.setMaximumSize(new java.awt.Dimension(96, 18));
        jLabel3.setMinimumSize(new java.awt.Dimension(96, 18));
        jLabel3.setPreferredSize(new java.awt.Dimension(96, 18));

        txt_GT.setEnabled(false);
        txt_GT.setMaximumSize(new java.awt.Dimension(160, 25));
        txt_GT.setMinimumSize(new java.awt.Dimension(160, 25));
        txt_GT.setPreferredSize(new java.awt.Dimension(160, 25));

        jLabel4.setText("Giới Tính");
        jLabel4.setMaximumSize(new java.awt.Dimension(96, 18));
        jLabel4.setMinimumSize(new java.awt.Dimension(96, 18));
        jLabel4.setPreferredSize(new java.awt.Dimension(96, 18));

        txt_EmailNV.setEnabled(false);
        txt_EmailNV.setMaximumSize(new java.awt.Dimension(160, 25));
        txt_EmailNV.setMinimumSize(new java.awt.Dimension(160, 25));
        txt_EmailNV.setPreferredSize(new java.awt.Dimension(160, 25));

        jLabel5.setText("Email");
        jLabel5.setMaximumSize(new java.awt.Dimension(96, 18));
        jLabel5.setMinimumSize(new java.awt.Dimension(96, 18));
        jLabel5.setPreferredSize(new java.awt.Dimension(96, 18));

        txt_SDTNV.setEnabled(false);
        txt_SDTNV.setMaximumSize(new java.awt.Dimension(160, 25));
        txt_SDTNV.setMinimumSize(new java.awt.Dimension(160, 25));
        txt_SDTNV.setPreferredSize(new java.awt.Dimension(160, 25));

        jLabel6.setText("SĐT");
        jLabel6.setMaximumSize(new java.awt.Dimension(96, 18));
        jLabel6.setMinimumSize(new java.awt.Dimension(96, 18));
        jLabel6.setPreferredSize(new java.awt.Dimension(96, 18));

        txt_DiaChi.setEnabled(false);
        txt_DiaChi.setMaximumSize(new java.awt.Dimension(160, 25));
        txt_DiaChi.setMinimumSize(new java.awt.Dimension(160, 25));
        txt_DiaChi.setPreferredSize(new java.awt.Dimension(160, 25));

        jLabel7.setText("Địa Chỉ");
        jLabel7.setMaximumSize(new java.awt.Dimension(124, 23));
        jLabel7.setMinimumSize(new java.awt.Dimension(124, 23));
        jLabel7.setPreferredSize(new java.awt.Dimension(124, 23));

        txt_Luong.setEnabled(false);
        txt_Luong.setMaximumSize(new java.awt.Dimension(160, 25));
        txt_Luong.setMinimumSize(new java.awt.Dimension(160, 25));
        txt_Luong.setPreferredSize(new java.awt.Dimension(160, 25));

        jLabel8.setText("Vị Trí Công Việc");
        jLabel8.setMaximumSize(new java.awt.Dimension(96, 18));
        jLabel8.setMinimumSize(new java.awt.Dimension(96, 18));
        jLabel8.setPreferredSize(new java.awt.Dimension(96, 18));

        txt_IDTaiKhoan.setEnabled(false);
        txt_IDTaiKhoan.setMaximumSize(new java.awt.Dimension(160, 25));
        txt_IDTaiKhoan.setMinimumSize(new java.awt.Dimension(160, 25));
        txt_IDTaiKhoan.setPreferredSize(new java.awt.Dimension(160, 25));

        jLabel9.setText("ID Tài Khoản");
        jLabel9.setMaximumSize(new java.awt.Dimension(96, 18));
        jLabel9.setMinimumSize(new java.awt.Dimension(96, 18));
        jLabel9.setPreferredSize(new java.awt.Dimension(96, 18));

        txt_VTCV.setEnabled(false);
        txt_VTCV.setMaximumSize(new java.awt.Dimension(160, 25));
        txt_VTCV.setMinimumSize(new java.awt.Dimension(160, 25));
        txt_VTCV.setPreferredSize(new java.awt.Dimension(160, 25));

        jLabel10.setText("Lương");
        jLabel10.setMaximumSize(new java.awt.Dimension(124, 23));
        jLabel10.setMinimumSize(new java.awt.Dimension(124, 23));
        jLabel10.setPreferredSize(new java.awt.Dimension(124, 23));

        jLabel11.setText("Ngày Sinh");
        jLabel11.setMaximumSize(new java.awt.Dimension(96, 18));
        jLabel11.setMinimumSize(new java.awt.Dimension(96, 18));
        jLabel11.setPreferredSize(new java.awt.Dimension(96, 18));

        jLabel12.setText("Ngày Vào Làm");
        jLabel12.setMaximumSize(new java.awt.Dimension(124, 23));
        jLabel12.setMinimumSize(new java.awt.Dimension(124, 23));
        jLabel12.setPreferredSize(new java.awt.Dimension(124, 23));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel1.setMaximumSize(new java.awt.Dimension(486, 125));
        jPanel1.setMinimumSize(new java.awt.Dimension(486, 125));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(486, 125));

        jLabel13.setText("Tìm Kiếm Theo");
        jLabel13.setMaximumSize(new java.awt.Dimension(96, 18));
        jLabel13.setMinimumSize(new java.awt.Dimension(96, 18));
        jLabel13.setPreferredSize(new java.awt.Dimension(96, 18));

        cmb_TimKiem.setMaximumSize(new java.awt.Dimension(294, 29));
        cmb_TimKiem.setMinimumSize(new java.awt.Dimension(294, 29));
        cmb_TimKiem.setPreferredSize(new java.awt.Dimension(294, 29));

        jLabel14.setText("Nhập");
        jLabel14.setMaximumSize(new java.awt.Dimension(96, 18));
        jLabel14.setMinimumSize(new java.awt.Dimension(96, 18));
        jLabel14.setPreferredSize(new java.awt.Dimension(96, 18));

        txt_TimKiem.setMaximumSize(new java.awt.Dimension(294, 29));
        txt_TimKiem.setMinimumSize(new java.awt.Dimension(294, 29));
        txt_TimKiem.setPreferredSize(new java.awt.Dimension(294, 29));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmb_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txt_TimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_AddTK.setBackground(new java.awt.Color(3, 172, 220));
        btn_AddTK.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_AddTK.setForeground(new java.awt.Color(255, 255, 255));
        btn_AddTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-add-administrator-26.png"))); // NOI18N
        btn_AddTK.setText("Thêm");
        btn_AddTK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_AddTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddTKActionPerformed(evt);
            }
        });

        btn_ResetSearch.setBackground(new java.awt.Color(3, 172, 220));
        btn_ResetSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_ResetSearch.setForeground(new java.awt.Color(255, 255, 255));
        btn_ResetSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-reset-26 (1).png"))); // NOI18N
        btn_ResetSearch.setText("Làm mới");
        btn_ResetSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_ResetSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ResetSearchActionPerformed(evt);
            }
        });

        txt_NgaySinh.setEnabled(false);
        txt_NgaySinh.setMaximumSize(new java.awt.Dimension(240, 30));
        txt_NgaySinh.setMinimumSize(new java.awt.Dimension(240, 30));
        txt_NgaySinh.setPreferredSize(new java.awt.Dimension(240, 30));

        txt_NVL.setEnabled(false);
        txt_NVL.setMaximumSize(new java.awt.Dimension(240, 30));
        txt_NVL.setMinimumSize(new java.awt.Dimension(240, 30));
        txt_NVL.setPreferredSize(new java.awt.Dimension(240, 30));

        javax.swing.GroupLayout info_NVLayout = new javax.swing.GroupLayout(info_NV);
        info_NV.setLayout(info_NVLayout);
        info_NVLayout.setHorizontalGroup(
            info_NVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(info_NVLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(info_NVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_MaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_EmailNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Luong, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(info_NVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_TenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_SDTNV, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_IDTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(info_NVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(info_NVLayout.createSequentialGroup()
                        .addGroup(info_NVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_GT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_DiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67)
                        .addGroup(info_NVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_NVL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_NgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(info_NVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_AddTK, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_ResetSearch))
                        .addGap(26, 26, 26))
                    .addGroup(info_NVLayout.createSequentialGroup()
                        .addGroup(info_NVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_VTCV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(140, 140, 140)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        info_NVLayout.setVerticalGroup(
            info_NVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(info_NVLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(info_NVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(info_NVLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(btn_ResetSearch))
                    .addGroup(info_NVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(info_NVLayout.createSequentialGroup()
                            .addGroup(info_NVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(info_NVLayout.createSequentialGroup()
                                    .addGroup(info_NVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(info_NVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txt_TenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt_GT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(info_NVLayout.createSequentialGroup()
                                    .addGap(24, 24, 24)
                                    .addComponent(txt_MaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(info_NVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(info_NVLayout.createSequentialGroup()
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_DiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(info_NVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(info_NVLayout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_SDTNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(info_NVLayout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_EmailNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(2, 2, 2))
                        .addGroup(info_NVLayout.createSequentialGroup()
                            .addGap(5, 5, 5)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(info_NVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btn_AddTK)
                                .addComponent(txt_NgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(21, 21, 21)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_NVL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20)
                .addGroup(info_NVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(info_NVLayout.createSequentialGroup()
                        .addGroup(info_NVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(info_NVLayout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_VTCV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(info_NVLayout.createSequentialGroup()
                                .addGroup(info_NVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(info_NVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_Luong, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_IDTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(31, 31, 31)))
                .addGap(17, 17, 17))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách nhân viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel2.setMaximumSize(new java.awt.Dimension(1368, 714));
        jPanel2.setMinimumSize(new java.awt.Dimension(1166, 714));
        jPanel2.setPreferredSize(new java.awt.Dimension(1360, 714));

        table_NhanVien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        table_NhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Nhân Viên", "Tên Nhân Viên", "Ngày", "GT", "Địa Chỉ", "SĐT", "Email", "Vị Trí", "Lương", "NVL", "IDTK", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_NhanVien.setMaximumSize(new java.awt.Dimension(1368, 1000));
        table_NhanVien.setMinimumSize(new java.awt.Dimension(1147, 349));
        table_NhanVien.setPreferredSize(new java.awt.Dimension(1300, 700));
        table_NhanVien.setRequestFocusEnabled(false);
        table_NhanVien.setRowHeight(40);
        table_NhanVien.setSelectionBackground(new java.awt.Color(57, 137, 111));
        table_NhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_NhanVienMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_NhanVien);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1344, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addComponent(info_NV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1370, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(info_NV, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AddTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddTKActionPerformed
        // TODO add your handling code here:
        NhanVienModule acc = null;
        try {
            acc = new NhanVienModule(NhanVienForm.this, true);
        } catch (SQLException ex) {
            Logger.getLogger(NhanVienForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        acc.txt_MaNV.setText(loadIDNV());
        acc.txt_MaNV.setEnabled(false);
        acc.setVisible(true);
    }//GEN-LAST:event_btn_AddTKActionPerformed

    private void btn_ResetSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ResetSearchActionPerformed
        // TODO add your handling code here:
        txt_TimKiem.setText("");
        cmb_TimKiem.setSelectedIndex(0);
        clearTxt();
        loadDataTbl();
    }//GEN-LAST:event_btn_ResetSearchActionPerformed

    private void clearTxt()
    {
        txt_MaNV.setText("");
        txt_TenNV.setText("");
        txt_NgaySinh.setText("");
        txt_GT.setText("");
        txt_DiaChi.setText("");
        txt_SDTNV.setText("");
        txt_EmailNV.setText("");
        txt_VTCV.setText("");
        txt_Luong.setText("");
        txt_NVL.setText("");
        txt_IDTaiKhoan.setText("");
    }
    
    private void table_NhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_NhanVienMouseClicked
        // TODO add your handling code here:
        int row = table_NhanVien.getSelectedRow();
        if(row != -1)
        {
            txt_MaNV.setText(table_NhanVien.getValueAt(row, 0).toString());
            txt_TenNV.setText(table_NhanVien.getValueAt(row, 1).toString());
            txt_NgaySinh.setText(table_NhanVien.getValueAt(row, 2).toString());
            txt_GT.setText(table_NhanVien.getValueAt(row, 3).toString());
            txt_DiaChi.setText(table_NhanVien.getValueAt(row, 4).toString());
            txt_SDTNV.setText(table_NhanVien.getValueAt(row, 5).toString());
            txt_EmailNV.setText(table_NhanVien.getValueAt(row, 6).toString());
            txt_VTCV.setText(table_NhanVien.getValueAt(row, 7).toString());
            txt_Luong.setText(table_NhanVien.getValueAt(row, 8).toString());
            txt_NVL.setText(table_NhanVien.getValueAt(row, 9).toString());
                        txt_IDTaiKhoan.setText(table_NhanVien.getValueAt(row, 10).toString());
            if(txt_IDTaiKhoan.getText().toString().isEmpty())
            {
                txt_IDTaiKhoan.setText("NULL");
            }


        }
        
        else
        {
            clearTxt();
        }
    }//GEN-LAST:event_table_NhanVienMouseClicked
    
    public void loadDataTbl()
    {
        table_NhanVien.setModel(tblmodel);
        try
        {
            tblmodel.setRowCount(0);
            con = nhom13_shopquanaothethao.Connection.GetConnection();
            String sql = "SELECT * FROM NHANVIEN";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next())
            {
                Object[] row = { rs.getString("IDNhanVien"), rs.getString("TenNhanVien"), rs.getString("NgaySinh"), rs.getString("GioiTinh"), rs.getString("DiaChi"), rs.getString("SDT"), rs.getString("Email"), rs.getString("ViTriCongViec"), rs.getString("Luong"), rs.getString("NgayVaoLam"), rs.getString("IDTaiKhoan")};
                tblmodel.addRow(row);
            }
           
            st.close();
            rs.close();
            con.close();
        }
        catch (SQLException e)
        {
            e.printStackTrace();
        }
    }
    
    private void loadDataCBB()
    {
        cmb_TimKiem.removeAllItems();
        for(int i = 0; i < table_NhanVien.getColumnCount() - 1; i++)
        {
            cmb_TimKiem.addItem(table_NhanVien.getColumnName(i));
        }
    }
    
    public String loadIDNV()
    {            
        String IDNVAuto = "";
        try
        {
            con = nhom13_shopquanaothethao.Connection.GetConnection();
            String sql = "SELECT TOP 1 IDNhanVien FROM NHANVIEN ORDER BY IDNhanVien DESC";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            if (rs.next())
            {
                int lastID = Integer.parseInt(rs.getString("IDNhanVien").substring(2));
                int lastNumber = lastID + 1;
                IDNVAuto = "NV" + String.format("%03d", lastNumber);
            }
            else
            {
                IDNVAuto = "NV001";
            }
        }
        catch (SQLException e)
        {
            e.printStackTrace();
        }
        
        return IDNVAuto;
    }
    
    private void Search()
    {
        String txt_search = txt_TimKiem.getText().trim();
        Object selectedItem = cmb_TimKiem.getSelectedItem();
        if (selectedItem != null)
        {
            if (txt_search.isEmpty())
            {
                loadDataTbl();
            }
            else
            {
                try
                {
                    con = nhom13_shopquanaothethao.Connection.GetConnection();
                    String sql = "SELECT * FROM NHANVIEN WHERE ";
                    if (cmb_TimKiem.getSelectedItem().toString().equals("IDTK"))
                    {
                        sql += "IDTaiKhoan LIKE ?";
                    }
                    else if (cmb_TimKiem.getSelectedItem().toString().equals("Mã Nhân Viên"))
                    {
                        sql += "IDNhanVien LIKE ?";
                    }
                    else if (cmb_TimKiem.getSelectedItem().toString().equals("Tên Nhân Viên"))
                    {
                        sql += "TenNhanVien LIKE ?";
                    }
                    
                    else if (cmb_TimKiem.getSelectedItem().toString().equals("Ngày"))
                    {
                        sql += "NgaySinh LIKE ?";
                    }
                    
                     else if (cmb_TimKiem.getSelectedItem().toString().equals("GT"))
                    {
                        sql += "GioiTinh LIKE ?";
                    }
                    
                     else if (cmb_TimKiem.getSelectedItem().toString().equals("Địa Chỉ"))
                    {
                        sql += "DiaChi LIKE ?";
                    }
                    
                     else if (cmb_TimKiem.getSelectedItem().toString().equals("SĐT"))
                    {
                        sql += "SDT LIKE ?";
                    }
                    
                     else if (cmb_TimKiem.getSelectedItem().toString().equals("Email"))
                    {
                        sql += "Email LIKE ?";
                    }
                    
                     else if (cmb_TimKiem.getSelectedItem().toString().equals("Vị Trí"))
                    {
                        sql += "ViTriCongViec LIKE ?";
                    }
                    
                     else if (cmb_TimKiem.getSelectedItem().toString().equals("Lương"))
                    {
                        sql += "Luong LIKE ?";
                    }
                    
                     else if (cmb_TimKiem.getSelectedItem().toString().equals("NVL"))
                    {
                        sql += "NgayVaoLam LIKE ?";
                    }

                    PreparedStatement preparedStatement = con.prepareStatement(sql);
                    preparedStatement.setString(1, "%" + txt_search + "%");
                    ResultSet rs = preparedStatement.executeQuery();
                    
                    tblmodel.setRowCount(0);
                    while (rs.next())
                    {
                        Object[] row = { rs.getString("IDNhanVien"), rs.getString("TenNhanVien"), rs.getString("NgaySinh"), rs.getString("GioiTinh"), rs.getString("DiaChi"), rs.getString("SDT"), rs.getString("Email"), rs.getString("ViTriCongViec"), rs.getString("Luong"), rs.getString("NgayVaoLam"), rs.getString("IDTaiKhoan") };
                        tblmodel.addRow(row);
                    }
                    preparedStatement.close();
                    rs.close();
                    con.close();
                }
                catch (SQLException e)
                {
                    e.printStackTrace();
                }
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn tìm kiếm theo", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
            
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optiotxtMaNV     /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhanVienForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhanVienForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhanVienForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhanVienForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NhanVienForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_AddTK;
    private javax.swing.JButton btn_ResetSearch;
    private javax.swing.JComboBox<String> cmb_TimKiem;
    private javax.swing.JPanel info_NV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTable table_NhanVien;
    private javax.swing.JTextField txt_DiaChi;
    private javax.swing.JTextField txt_EmailNV;
    private javax.swing.JTextField txt_GT;
    private javax.swing.JTextField txt_IDTaiKhoan;
    private javax.swing.JTextField txt_Luong;
    private javax.swing.JTextField txt_MaNV;
    private javax.swing.JTextField txt_NVL;
    private javax.swing.JTextField txt_NgaySinh;
    private javax.swing.JTextField txt_SDTNV;
    private javax.swing.JTextField txt_TenNV;
    private javax.swing.JTextField txt_TimKiem;
    private javax.swing.JTextField txt_VTCV;
    // End of variables declaration//GEN-END:variables
}
