/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package nhom13_shopquanaothethao;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author ACER
 */
public class Product extends javax.swing.JPanel {

    /**
     * Creates new form Product
     */
    public String idsp, tensp, category, idncc;
    public String size;
    public String img;
    public int giaban;
    
    public BanHangForm BHF;
    public KhoHangForm KHF;
    
    public String getIdsp() {
        return idsp;
    }

    public void setIdsp(String idsp) {
        this.idsp = idsp;
    }

    public String getTensp() {
        return tensp;
    }

    public void setTensp(String tensp) {
        this.tensp = tensp;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }
    
    public String getIdncc() {
        return idncc;
    }

    public void setIdncc(String idncc) {
        this.idncc = idncc;
    }
    
    public String getProductSize() {
        return size;
    }

    public void setProductSize(String size) {
        this.size = size;
    }
    
    public String getImg() {
        return img;
    }

    public void setImg(String img) {
        this.img = img;
    }

    public int getGiaban() {
        return giaban;
    }

    public void setGiaban(int giaban) {
        this.giaban = giaban;
    }
    
    public Product(BanHangForm bf, KhoHangForm kf, String idsp, String tensp, String category, String idncc, String size, int price, String image) {
        initComponents();
        this.BHF = bf;
        this.KHF = kf;
        this.lbl_TenSP.setText(tensp);
        this.lbl_Size.setText("Size: " + size);
        
        ImageIcon icon = new ImageIcon(getClass().getResource("/Images/" + image));
        Image imgs = icon.getImage();

        
        Image scaledImg = imgs.getScaledInstance(100, 100, Image.SCALE_SMOOTH);
        this.lbl_ImgSP.setIcon(new ImageIcon(scaledImg));
        this.idsp = idsp;
        this.tensp = tensp;
        this.category = category;
        this.idncc = idncc;
        this.size = size;
        this.giaban = price;
        this.img = image;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_ImgSP = new javax.swing.JLabel();
        lbl_TenSP = new javax.swing.JLabel();
        lbl_Size = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_ImgSP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_ImgSP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_ImgSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_ImgSPMouseClicked(evt);
            }
        });
        add(lbl_ImgSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 210, 120));

        lbl_TenSP.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_TenSP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_TenSP.setText("ProductName");
        add(lbl_TenSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 210, 20));

        lbl_Size.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_Size.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Size.setText("Size");
        lbl_Size.setToolTipText("");
        add(lbl_Size, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 146, 210, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_ImgSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ImgSPMouseClicked
        // TODO add your handling code here:
        if (KHF == null)
        {
            BanHangModule module = new BanHangModule(this, BHF);
            module.setVisible(true);
        }
        else
        {
            KhoHangModule module = new KhoHangModule(this, KHF);
            module.setVisible(true);
        }
    }//GEN-LAST:event_lbl_ImgSPMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_ImgSP;
    private javax.swing.JLabel lbl_Size;
    private javax.swing.JLabel lbl_TenSP;
    // End of variables declaration//GEN-END:variables
}
